env: dev
node_port: 3000
node_env: dev
app_repo: "https://github.com/fasih6/3-tier-NodejsApp-project.git"
app_dir: /opt/app
db_name: crud_app
db_user: root
db_host: "{{ groups['db'][0] }}"
db_password: "{{ vault_db_password }}"
jwt_secret: "{{ vault_jwt_secret }}"
